### ISSUE TITLE
Consider Opt-in for more-frequent monitoring

### ISSUE THREAD

**Issue by willscott** [thingless/torweather#1]
Especially for high-bandwidth relays, 48 hours is a long time. It would be useful for relays to be able to opt-in to a more frequent monitoring so that they could be contacted more quickly after they've stopped responding.

**Comment by richardklafter** [comment]
Thanks for the suggestion! 

To be honest it is unclear how much value the tor community gets from this project. We hacked it together one night when we heard they were deprecating the old Tor Weather to maintain what we thought was the most important features of Tor Weather, notifying casual Tor relay operators of extended downtime (it has saved my relay several times since then). One of the requirements when we built it was for it to be easy to maintain (the old Tor Weather was depreciated because it was too much work to maintain).

That being said, we might or might not do it but if you create a pull request we will almost certainly accept it!

Even if ya choose not to submit a PR, it is good to hear someone gets some value from the project. We get ~1 email a month from someone replying to a downtime email but your the first GitHub issue :)
